version: '3.8'

services:
  mariadb:
    image: mariadb:11
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: cyberlaw
      MYSQL_USER: cyberlaw
      MYSQL_PASSWORD: cyberlawpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  cyberlaw-app:
    build: .
    depends_on:
      - mariadb
    environment:
      DB_HOST: mariadb
      DB_USER: cyberlaw
      DB_PASSWORD: cyberlawpass
      DB_NAME: cyberlaw
    command: ["cron", "-f"]

volumes:
  db_data:
